version: '3.9'

services:
  webfrontend:
    container_name: webfrontend
    restart: always
    image: php:8.0-apache
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80

  db:
    container_name: mysql
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=mini
      - MYSQL_ROOT_PASSWORD=mini
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

  jenkins:
    container_name: jenkins
    image: docker.io/jenkins/jenkins:lts-jdk11
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - "./jenkins-data:/var/jenkins_home:rw"
    user: "0:0"

volumes:
  db:
    driver: local
